#-------------------------------------------------------------------------------
# Workflow configuration
#-------------------------------------------------------------------------------

name: "Desktop CI builds (cmake)"
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  APP_NAME: "ResourceDragon"
  APP_VERSION: "0.0.1"

jobs:
  ## GNU/Linux build ###########################################################
  build-linux:
    name: "Linux CI build"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0

      # Cache submodules
      - name: Cache submodules
        uses: actions/cache@v3
        with:
          path: .git/modules
          key: submodules-linux-${{ hashFiles('.gitmodules') }}
          restore-keys: |
            submodules-linux-

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Install Clang from llvm.sh
        run: |
          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"

      - name: Install dependencies (from package manager)
        run: |
          sudo apt-get install libgl-dev libxkbcommon-x11-dev libx11-xcb-dev libzstd-dev \
          libxcb1 libxkbcommon0 libxkbcommon-x11-0 libx11-xcb1 libwayland-client0 \
          libwayland-cursor0 libwayland-egl1 libwayland-server0 cmake ninja-build \
          pkgconf libtool libfuse2 appstream libasound2 libasound2-dev \
          libpipewire-0.3-0 libpipewire-0.3-dev libaudio2 libaudio-dev libcurl4-openssl-dev -y;

      - name: Build application
        run: ./build.sh

      - name: Deploy application
        run: ./deploy_linux.sh -i -c -p

      - name: Upload application ZIP
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.APP_NAME}}-${{env.APP_VERSION}}-linux64.tar.gz
          path: ${{env.APP_NAME}}-${{env.APP_VERSION}}-linux64.tar.gz

      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.APP_NAME}}-${{env.APP_VERSION}}-linux64.AppImage
          path: ${{env.APP_NAME}}-${{env.APP_VERSION}}-linux64.AppImage

  ## Windows build ############################################################
  build-windows:
    name: "Windows CI build"
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0

      # Cache submodules
      - name: Cache submodules
        uses: actions/cache@v3
        with:
          path: .git/modules
          key: submodules-windows-${{ hashFiles('.gitmodules') }}
          restore-keys: |
            submodules-windows-

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Install NASM
        run: choco install nasm -y

      - name: Install LLVM (clang-cl)
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build application
        run: ./build.ps1
        shell: pwsh

      - name: Prepare Windows artifact bundle
        run: |
          cp build-win32/ResourceDragon.exe ./

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.APP_NAME}}-${{env.APP_VERSION}}-win64
          path: |
            fonts/
            scripts/
            ResourceDragon.exe
